### GET request for a company
GET http://localhost:8080/app?content=company
Accept: application/json

### GET request for a person
GET http://localhost:8080/app?content=person
Accept: application/json